_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
                - 71
            "2":
                - 1
                - 11
                - 49
                - 55
                - 71
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.8
            "6": 4.26.1
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
learning_rate:
    value: 1e-05
logging_step:
    value: 100
num_epoch:
    value: 3
savedir:
    value: ./checkpoints/bert-simple
train_batch_size:
    value: 8
use_wandb:
    value: true
validation:
    value: true
